Lots of changes
HerrSpace/ansible-role-letsencrypt pull request #2
Opened 2017-05-16 12:57 UTC by farhaven

I can split these out into separate MRs if necessary, but they should all be noncontroversial.

2017-05-16 20:20 UTC, RonjaPonja requested changes
Looks fine. I'd like to at least address the defautl/main.yml changes though.

2017-05-16 20:20 UTC, HerrSpace commented on defaults/main.yml
> -  example.com: [www.example.com, foo.example.com]
I'm a friend of have all relevant variables one might want to overwrite in the defaults/main.yml. I see why you wouldn't want to have this enabled though. Would it be acceptable to keep, but comment out letsencrypt_email and letsencrypt_cert_domains?

2017-05-16 20:20 UTC, HerrSpace commented on tasks/main.yml
> +  when: ansible_service_mgr == "systemd"
Can we define this as the default in defaults/main.yml?

2017-05-16 20:20 UTC, HerrSpace commented on tasks/main.yml
> +  when: ansible_service_mgr != "systemd"
Hmmm. Maybe we could just always add both lines?.. but I'm not sure.

2017-05-20 16:33 UTC, HerrSpace commented
Opinions? I will make the relevant changes if you think they are okay.

2018-05-04 08:19 UTC, merged

2018-05-04 08:19 UTC, RonjaPonja commented
Ahh, a well aged merge request. Good time to merge this, right? RIGHT?